In [ ]:
import nannyml as nml
from IPython.display import display

reference_df = nml.load_synthetic_binary_classification_dataset()[0]
analysis_df = nml.load_synthetic_binary_classification_dataset()[1]
display(reference_df.head())

,distance_from_office,salary_range,gas_price_per_litre,public_transportation_cost,wfh_prev_workday,workday,tenure,identifier,work_home_actual,timestamp,y_pred_proba,period,y_pred
0,5.962247,40K - 60K €,2.119485,8.568058,False,Friday,0.212653,0,1,2014-05-09 22:27:20,0.99,reference,1
1,0.535872,40K - 60K €,2.357199,5.425382,True,Tuesday,4.927549,1,0,2014-05-09 22:59:32,0.07,reference,0
2,1.969519,40K - 60K €,2.366849,8.247158,False,Monday,0.520817,2,1,2014-05-09 23:48:25,1.00,reference,1
3,2.530410,20K - 40K €,2.318722,7.944251,False,Tuesday,0.453649,3,1,2014-05-10 01:12:09,0.98,reference,1
4,2.253635,60K+ €,2.221265,8.884478,True,Thursday,5.695263,4,1,2014-05-10 02:21:34,0.99,reference,1

In [ ]:
print(reference_df.head().to_markdown(tablefmt="grid"))

+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+
|    |   distance_from_office | salary_range   |   gas_price_per_litre |   public_transportation_cost | wfh_prev_workday   | workday   |   tenure |   identifier |   work_home_actual | timestamp           |   y_pred_proba | period    |   y_pred |
+====+========================+================+=======================+==============================+====================+===========+==========+==============+====================+=====================+================+===========+==========+
|  0 |               5.96225  | 40K - 60K €    |               2.11948 |                      8.56806 | False              | Friday    | 0.212653 |            0 |                  1 | 2014-05-09 22:27:20 |           0.99 | reference |        1 |
+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+
|  1 |               0.535872 | 40K - 60K €    |               2.3572  |                      5.42538 | True               | Tuesday   | 4.92755  |            1 |                  0 | 2014-05-09 22:59:32 |           0.07 | reference |        0 |
+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+
|  2 |               1.96952  | 40K - 60K €    |               2.36685 |                      8.24716 | False              | Monday    | 0.520817 |            2 |                  1 | 2014-05-09 23:48:25 |           1    | reference |        1 |
+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+
|  3 |               2.53041  | 20K - 40K €    |               2.31872 |                      7.94425 | False              | Tuesday   | 0.453649 |            3 |                  1 | 2014-05-10 01:12:09 |           0.98 | reference |        1 |
+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+
|  4 |               2.25364  | 60K+ €         |               2.22127 |                      8.88448 | True               | Thursday  | 5.69526  |            4 |                  1 | 2014-05-10 02:21:34 |           0.99 | reference |        1 |
+----+------------------------+----------------+-----------------------+------------------------------+--------------------+-----------+----------+--------------+--------------------+---------------------+----------------+-----------+----------+

In [ ]:
calc = nml.StatisticalOutputDriftCalculator(
    y_pred='y_pred',
    y_pred_proba='y_pred_proba',
    timestamp_column_name='timestamp',
    problem_type='classification_binary'
)
calc.fit(reference_df)
results = calc.calculate(analysis_df)

In [ ]:
display(results.data)

,key,chunk_index,start_index,end_index,start_date,end_date,y_pred_chi2,y_pred_p_value,y_pred_alert,y_pred_threshold,y_pred_proba_dstat,y_pred_proba_p_value,y_pred_proba_alert,y_pred_proba_threshold
0,[0:4999],0,0,4999,2017-08-31 04:20:00,2018-01-02 00:45:44,7.442383,0.006,True,0.05,0.02530,0.006,True,0.05
1,[5000:9999],1,5000,9999,2018-01-02 01:13:11,2018-05-01 13:10:10,1.800169,0.180,False,0.05,0.01230,0.494,False,0.05
2,[10000:14999],2,10000,14999,2018-05-01 14:25:25,2018-09-01 15:40:40,1.728529,0.189,False,0.05,0.01642,0.170,False,0.05
3,[15000:19999],3,15000,19999,2018-09-01 16:19:07,2018-12-31 10:11:21,1.589612,0.207,False,0.05,0.01058,0.685,False,0.05
4,[20000:24999],4,20000,24999,2018-12-31 10:38:45,2019-04-30 11:01:30,0.060896,0.805,False,0.05,0.01408,0.325,False,0.05
5,[25000:29999],5,25000,29999,2019-04-30 11:02:00,2019-09-01 00:24:27,12.512107,0.000,True,0.05,0.13070,0.000,True,0.05
6,[30000:34999],6,30000,34999,2019-09-01 00:28:54,2019-12-31 09:09:12,11.393384,0.001,True,0.05,0.12730,0.000,True,0.05
7,[35000:39999],7,35000,39999,2019-12-31 10:07:15,2020-04-30 11:46:53,9.813532,0.002,True,0.05,0.13110,0.000,True,0.05
8,[40000:44999],8,40000,44999,2020-04-30 12:04:32,2020-09-01 02:46:02,3.786524,0.052,False,0.05,0.11970,0.000,True,0.05
9,[45000:49999],9,45000,49999,2020-09-01 02:46:13,2021-01-01 04:29:32,27.990040,0.000,True,0.05,0.13752,0.000,True,0.05

In [ ]:
print(results.data.to_markdown(tablefmt="grid"))

+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|    | key           |   chunk_index |   start_index |   end_index | start_date          | end_date            |   y_pred_chi2 |   y_pred_p_value | y_pred_alert   |   y_pred_threshold |   y_pred_proba_dstat |   y_pred_proba_p_value | y_pred_proba_alert   |   y_pred_proba_threshold |
+====+===============+===============+===============+=============+=====================+=====================+===============+==================+================+====================+======================+========================+======================+==========================+
|  0 | [0:4999]      |             0 |             0 |        4999 | 2017-08-31 04:20:00 | 2018-01-02 00:45:44 |     7.44238   |            0.006 | True           |               0.05 |              0.0253  |                  0.006 | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  1 | [5000:9999]   |             1 |          5000 |        9999 | 2018-01-02 01:13:11 | 2018-05-01 13:10:10 |     1.80017   |            0.18  | False          |               0.05 |              0.0123  |                  0.494 | False                |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  2 | [10000:14999] |             2 |         10000 |       14999 | 2018-05-01 14:25:25 | 2018-09-01 15:40:40 |     1.72853   |            0.189 | False          |               0.05 |              0.01642 |                  0.17  | False                |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  3 | [15000:19999] |             3 |         15000 |       19999 | 2018-09-01 16:19:07 | 2018-12-31 10:11:21 |     1.58961   |            0.207 | False          |               0.05 |              0.01058 |                  0.685 | False                |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  4 | [20000:24999] |             4 |         20000 |       24999 | 2018-12-31 10:38:45 | 2019-04-30 11:01:30 |     0.0608958 |            0.805 | False          |               0.05 |              0.01408 |                  0.325 | False                |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  5 | [25000:29999] |             5 |         25000 |       29999 | 2019-04-30 11:02:00 | 2019-09-01 00:24:27 |    12.5121    |            0     | True           |               0.05 |              0.1307  |                  0     | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  6 | [30000:34999] |             6 |         30000 |       34999 | 2019-09-01 00:28:54 | 2019-12-31 09:09:12 |    11.3934    |            0.001 | True           |               0.05 |              0.1273  |                  0     | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  7 | [35000:39999] |             7 |         35000 |       39999 | 2019-12-31 10:07:15 | 2020-04-30 11:46:53 |     9.81353   |            0.002 | True           |               0.05 |              0.1311  |                  0     | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  8 | [40000:44999] |             8 |         40000 |       44999 | 2020-04-30 12:04:32 | 2020-09-01 02:46:02 |     3.78652   |            0.052 | False          |               0.05 |              0.1197  |                  0     | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+
|  9 | [45000:49999] |             9 |         45000 |       49999 | 2020-09-01 02:46:13 | 2021-01-01 04:29:32 |    27.99      |            0     | True           |               0.05 |              0.13752 |                  0     | True                 |                     0.05 |
+----+---------------+---------------+---------------+-------------+---------------------+---------------------+---------------+------------------+----------------+--------------------+----------------------+------------------------+----------------------+--------------------------+

In [ ]:
score_drift_fig = results.plot(kind='score_drift', plot_reference=True)
score_drift_fig.show()

In [ ]:
score_drift_fig.write_image('../_static/tutorials/detecting_data_drift/model_outputs/binary/drift-guide-score-drift.svg')

In [ ]:
score_distribution_fig = results.plot(kind='score_distribution', plot_reference=True)
score_distribution_fig.show()

In [ ]:
score_distribution_fig.write_image('../_static/tutorials/detecting_data_drift/model_outputs/binary/drift-guide-score-distribution.svg')

In [ ]:
prediction_drift_fig = results.plot(kind='prediction_drift', plot_reference=True)
prediction_drift_fig.show()

In [ ]:
prediction_drift_fig.write_image('../_static/tutorials/detecting_data_drift/model_outputs/binary/drift-guide-prediction-drift.svg')

In [ ]:
prediction_distribution_fig = results.plot(kind='prediction_distribution', plot_reference=True)
prediction_distribution_fig.show()

In [ ]:
prediction_distribution_fig.write_image('../_static/tutorials/detecting_data_drift/model_outputs/binary/drift-guide-prediction-distribution.svg')